                                                                                                                                                                                                                                                                                                                                import React from "react";

                                                                                                                                                                                                                                                                                                                                // About component: displays the blog logo and a short description.
                                                                                                                                                                                                                                                                                                                                // Props:
                                                                                                                                                                                                                                                                                                                                // - `image` (string): URL or imported asset for the blog logo. Defaults to a
                                                                                                                                                                                                                                                                                                                                //   placeholder image when not provided.
                                                                                                                                                                                                                                                                                                                                // - `about` (string): Short description text for the blog.
                                                                                                                                                                                                                                                                                                                                // Connected to: `App` — `App` passes `image` and `about` from `blog.js`.
                                                                                                                                                                                                                                                                                                                                function About({ image = "https://via.placeholder.com/215", about }) {
                                                                                                                                                                                                                                                                                                                                  return (
                                                                                                                                                                                                                                                                                                                                    <aside>
                                                                                                                                                                                                                                                                                                                                      <img src={image} alt="blog logo" />
                                                                                                                                                                                                                                                                                                                                      <p>{about}</p>
                                                                                                                                                                                                                                                                                                                                    </aside>
                                                                                                                                                                                                                                                                                                                                  );
                                                                                                                                                                                                                                                                                                                                }

                                                                                                                                                                                                                                                                                                                                export default About;
